# Generated by Django 4.0.6 on 2023-01-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainer_data',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trainer_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communicatin_skill', models.IntegerField()),
                ('content_delivered', models.IntegerField()),
                ('doubt_clarification', models.IntegerField()),
                ('technical_skill', models.IntegerField()),
                ('feedback', models.CharField(max_length=500)),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submit', to='feedback_details.trainer_data')),
            ],
        ),
    ]
