# Generated by Django 4.0.6 on 2023-01-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_feedback',
            name='review',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
