# Generated by Django 4.0.6 on 2023-01-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_details', '0002_trainer_feedback_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_feedback',
            name='train_id',
            field=models.CharField(max_length=30),
        ),
    ]
