# Generated by Django 4.0.6 on 2023-01-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_details', '0004_remove_trainer_feedback_train_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer_feedback',
            name='train_data',
        ),
        migrations.AddField(
            model_name='trainer_feedback',
            name='train_id',
            field=models.ForeignKey(default='EC0000', on_delete=django.db.models.deletion.CASCADE, related_name='code_submit', to='feedback_details.trainer_data'),
        ),
    ]
